using KursovayaP.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KursovayaP.ViewModel
{
    public class VMWeapons
    {
        public List<Weapon> Weapons { get; set; }

        public VMWeapons()
        {
            Weapons = new List<Weapon>
        {
                new Weapon { Name = "Песнь патруля пиков", Type = "Меч", BaseAttack = 42, SecondaryStat = "Сила атаки" },
                new Weapon { Name = "Отпущение грехов", Type = "Меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Ураку мисугири", Type = "Меч", BaseAttack = 44, SecondaryStat = "Сила атаки" },
                new Weapon { Name = "Блеск тихих вод", Type = "Меч", BaseAttack = 44, SecondaryStat = "Мастерство стихий" },
                new Weapon { Name = "Свет лиственного разреза", Type = "Меч", BaseAttack = 42, SecondaryStat = "Восстановление энергии" },
                new Weapon { Name = "Ключ Хадж-нисут", Type = "Меч", BaseAttack = 44, SecondaryStat = "Мастерство стихий" },
                new Weapon { Name = "Харан гэппаку фуцу", Type = "Меч", BaseAttack = 44, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Рассекающий туман", Type = "Меч", BaseAttack = 42, SecondaryStat = "Мастерство стихий" },
                new Weapon { Name = "Клятва свободы", Type = "Меч", BaseAttack = 42, SecondaryStat = "Сила атаки" },
                new Weapon { Name = "Меч Сокола", Type = "Меч", BaseAttack = 42, SecondaryStat = "Сила атаки" },
                new Weapon { Name = "Небесный меч", Type = "Меч", BaseAttack = 46, SecondaryStat = "Восстановление энергии" },
                new Weapon { Name = "Кромсатель пиков", Type = "Меч", BaseAttack = 42, SecondaryStat = "Сила атаки" },
                new Weapon { Name = "Драгоценный омут", Type = "Меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Алое перо звёздного грифа", Type = "Лук", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Сердечные струны дождя", Type = "Лук", BaseAttack = 42, SecondaryStat = "Мастерство стихий" },
                new Weapon { Name = "Первый великий фокус", Type = "Лук", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Охотничья тропа", Type = "Лук", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Аква симулякрум", Type = "Лук", BaseAttack = 42, SecondaryStat = "Мастерство стихий" },
                new Weapon { Name = "Полярная звезда", Type = "Лук", BaseAttack = 46, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Громовой пульс", Type = "Лук", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Элегия погибели", Type = "Лук", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Небесное крыло", Type = "Лук", BaseAttack = 48, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Лук Амоса", Type = "Лук", BaseAttack = 46, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Элегия Люмидус", Type = "Копьё", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Очертания алой луны", Type = "Копьё", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Посох алых песков", Type = "Копьё", BaseAttack = 44, SecondaryStat = "Мастерство стихий" },
                new Weapon { Name = "Усмиритель бед", Type = "Копьё", BaseAttack = 44, SecondaryStat = "Мастерство стихий" },
                new Weapon { Name = "Сияющая жатва", Type = "Копьё", BaseAttack = 44, SecondaryStat = "Мастерство стихий" },
                new Weapon { Name = "Покоритель вихря", Type = "Копьё", BaseAttack = 44, SecondaryStat = "Мастерство стихий" },
                new Weapon { Name = "Небесная ось", Type = "Копьё", BaseAttack = 48, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Нефритовый коршун", Type = "Копьё", BaseAttack = 44, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Посох Хомы", Type = "Копьё", BaseAttack = 44, SecondaryStat = "Мастерство стихий" },
                new Weapon { Name = "Клык Горного короля", Type = "Двуручный меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Вердикт", Type = "Двуручный меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Маяк тростникового моря", Type = "Двуручный меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Краснорогий камнеруб", Type = "Двуручный меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Песнь разбитых сосен", Type = "Двуручный меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Небесное величие", Type = "Двуручный меч", BaseAttack = 46, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Волчья погибель", Type = "Двуручный меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Некованый", Type = "Двуручный меч", BaseAttack = 44, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Лови волну", Type = "Катализатор", BaseAttack = 42, SecondaryStat = "Мастерство стихий" },
                new Weapon { Name = "Звонкий клич журавля", Type = "Катализатор", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Казначейский надзор", Type = "Катализатор", BaseAttack = 44, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Обряд вечного течения", Type = "Катализатор", BaseAttack = 44, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Великолепие лазурного свода", Type = "Катализатор", BaseAttack = 46, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Воспоминания Тулайтуллы", Type = "Катализатор", BaseAttack = 44, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Сновидения тысячи ночей", Type = "Катализатор", BaseAttack = 46, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Истина кагура", Type = "Катализатор", BaseAttack = 46, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Вечное лунное сияние", Type = "Катализатор", BaseAttack = 46, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Молитва святым ветрам", Type = "Катализатор", BaseAttack = 48, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Небесный атлас", Type = "Катализатор", BaseAttack = 48, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Память о пыли", Type = "Катализатор", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Бедствие Эшу", Type = "Меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Крепкая кость", Type = "Меч", BaseAttack = 44, SecondaryStat = "Сила атаки" },
                new Weapon { Name = "Флейта Эспицаль", Type = "Меч", BaseAttack = 42, SecondaryStat = "Мастерство стихий" },
                new Weapon { Name = "Меч Нарциссенкрейца", Type = "Меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Верфь", Type = "Меч", BaseAttack = 44, SecondaryStat = "Мастерство стихий" },
                new Weapon { Name = "Волчий клык", Type = "Меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Грандиозный финал глубин", Type = "Меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Перевозчик Флёв Сандр", Type = "Меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Токабо серверэ", Type = "Меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Лунное сияние ксифоса", Type = "Меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Деревянный клинок", Type = "Меч", BaseAttack = 40, SecondaryStat = "Мастерство стихий" },
                new Weapon { Name = "Кагоцурубэ Иссин", Type = "Меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Киноварное веретено", Type = "Меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Амэнома Кагэути", Type = "Меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Вспышка во тьме", Type = "Меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Осквернённое желание", Type = "Меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Меч нисхождения", Type = "Меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Стальное жало", Type = "Меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Драконий рык", Type = "Меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Прототип: Злоба", Type = "Меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Церемониальный меч", Type = "Меч", BaseAttack = 44, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Меч-флейта", Type = "Меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Чёрный меч", Type = "Меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Меч Фавония", Type = "Меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Меч аристократов", Type = "Меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Черногорский длинный меч", Type = "Меч", BaseAttack = 44, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Украшенные цветами перья", Type = "Лук", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Разбивающий цепи", Type = "Лук", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Выкованный из облаков", Type = "Лук", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Дальномер", Type = "Лук", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Наследник слепящего солнца", Type = "Лук", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Мелодия покоя", Type = "Лук", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Клюв ибиса", Type = "Лук", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Иссушитель", Type = "Лук", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Приближённый короля", Type = "Лук", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Гаснущие сумерки", Type = "Лук", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Луна Моун", Type = "Лук", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Хищник", Type = "Лук", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Хамаюми", Type = "Лук", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Вальс Нирваны Ночи", Type = "Лук", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Охотник во тьме", Type = "Лук", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Ода анемонии", Type = "Лук", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Черногорский боевой лук", Type = "Лук", BaseAttack = 44, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Составной лук", Type = "Лук", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Боевой лук Фавония", Type = "Лук", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Прототип: Полумесяц", Type = "Лук", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Зелёный лук", Type = "Лук", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Королевский лук", Type = "Лук", BaseAttack = 44, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Ржавый лук", Type = "Лук", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Церемониальный лук", Type = "Лук", BaseAttack = 44, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Бесструнный", Type = "Лук", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Крепящий горы шип", Type = "Копьё", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "След радуги", Type = "Копьё", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Диалог пустынных мудрецов", Type = "Копьё", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Бур рудоискателя", Type = "Копьё", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Баллада фьордов", Type = "Копьё", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Справедливая награда", Type = "Копьё", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Копьё послания ветров", Type = "Копьё", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Пронзающий луну", Type = "Копьё", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Режущий волны плавник", Type = "Копьё", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "«Улов»", Type = "Копьё", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Крест-копьё Китаин", Type = "Копьё", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Королевское копьё", Type = "Копьё", BaseAttack = 44, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Копьё Фавония", Type = "Копьё", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Каменное копьё", Type = "Копьё", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Смертельный бой", Type = "Копьё", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Прототип: Звёздный блеск", Type = "Копьё", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Копьё Драконьего хребта", Type = "Копьё", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Гроза драконов", Type = "Копьё", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Черногорская пика", Type = "Копьё", BaseAttack = 44, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Пика полумесяца", Type = "Копьё", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Плодотворный крюк", Type = "Двуручный меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Сотрясающий землю", Type = "Двуручный меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "«Магический супермеч высшего владыки»", Type = "Двуручный меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Переносная мотопила", Type = "Двуручный меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Говорящая палица", Type = "Двуручный меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Тень волны", Type = "Двуручный меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Цветок в латах", Type = "Двуручный меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Аквамарин Махайры", Type = "Двуручный меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Регалия леса", Type = "Двуручный меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Акуомару", Type = "Двуручный меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Благодатный владыка вод", Type = "Двуручный меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Кацурагикири Нагамаса", Type = "Двуручный меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Королевский двуручный меч", Type = "Двуручный меч", BaseAttack = 44, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Каменный меч", Type = "Двуручный меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Двуручный меч Фавония", Type = "Двуручный меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Прототип: Архаичный", Type = "Двуручный меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Черногорская бритва", Type = "Двуручный меч", BaseAttack = 44, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Церемониальный двуручный меч", Type = "Двуручный меч", BaseAttack = 44, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Меч драконьей кости", Type = "Двуручный меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Меч-колокол", Type = "Двуручный меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Белая тень", Type = "Двуручный меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Дождерез", Type = "Двуручный меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Заснеженное звёздное серебро", Type = "Двуручный меч", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Вихрь на волнах", Type = "Катализатор", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Кольцо Яшче", Type = "Катализатор", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Пепельный рог", Type = "Катализатор", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Песнь необъятной лазури", Type = "Катализатор", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Жертвенный нефрит", Type = "Катализатор", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Сверкание чистых вод", Type = "Катализатор", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Скитающаяся звезда", Type = "Катализатор", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Плод восполнения", Type = "Катализатор", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Око клятвы", Type = "Катализатор", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Кольцо Хакусин", Type = "Катализатор", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Истории Додоко", Type = "Катализатор", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Вино и песни", Type = "Катализатор", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Песнь странника", Type = "Катализатор", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Солнечная жемчужина", Type = "Катализатор", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Церемониальные мемуары", Type = "Катализатор", BaseAttack = 44, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Черногорский агат", Type = "Катализатор", BaseAttack = 44, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Королевский гримуар", Type = "Катализатор", BaseAttack = 44, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Прототип: Янтарь", Type = "Катализатор", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Морской атлас", Type = "Катализатор", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Кодекс Фавония", Type = "Катализатор", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Око сознания", Type = "Катализатор", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },
                new Weapon { Name = "Плод вечной мерзлоты", Type = "Катализатор", BaseAttack = 42, SecondaryStat = "Шанс Критического Удара" },

        };
        }
    }

}
